#!/bin/bash

echo "======================================"
echo "Firefox Extension ID Finder"
echo "======================================"
echo ""
echo "To find your extension ID:"
echo ""
echo "1. Open Firefox"
echo "2. Go to: about:debugging#/runtime/this-firefox"
echo "3. Find 'Offlyn Apply' extension in the list"
echo "4. Look for 'Internal UUID' or 'Extension ID'"
echo "5. Copy the entire ID (it looks like: {xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx})"
echo ""
echo "Once you have the ID, run:"
echo "  cd native-host"
echo "  node install-manifest.js"
echo ""
echo "And paste your extension ID when prompted."
echo ""
echo "======================================"
