#!/usr/bin/env bash
# Generated by install-manifest.js - uses full path to node so Firefox can start the host
cd "$(dirname "$0")"
exec "/Users/nishanthreddy/.nvm/versions/node/v22.16.0/bin/node" index.js
